server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:

          keycloak:
            client-id: oauth2-client-app
            client-secret: KaUeVyCxo76S4M662vOw8NJ1NWNtAD0s
            client-name: oauth2-client-app
            authorization-grant-type: authorization_code
            scope: openid,profile
            client-authentication-method: client_secret_basic
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
            provider: keycloak


        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/oauth2
            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
